### ISSUE TITLE
Shopping Basket

### ISSUE THREAD

**Issue by Sch3lp** [Sch3lp/FiAngulartje#4]
# Shopping Basket
Once at least one Sandwich was selected, a Basket icon should be displayed on the screen somewhere, along with the total price, and total Sandwiches in the Basket.

We might need to add a step in between clicking a Sandwich from the Products screen, that clarifies to the user that they're about to add a Sandwich to their Basket.

**Comment by toonborgers** [comment]
For the step inbetween, maybe just like 't Fiantje: a popup with a count and remark?

**Comment by toonborgers** [comment]
Fixed in pull request #24
