### ISSUE TITLE
Checkout

### ISSUE THREAD

**Issue by Sch3lp** [Sch3lp/FiAngulartje#5]
# Checkout
The Shopping Basket should get a button or something that allows a user to Checkout his current Basket.

# Overview
The Checkout page shows an overview of all the Sandwiches with their price and their commentary, and a total.

# Available actions
A user still has the chance to 
* Change their commentary (to fix typo's and what not)
* Remove Sandwiches from the current Basket
* Change the Bun type (dynamically changing the price)

There will be a confirm button of some kind that says "Yup, I'm ready to order now!", which provides the user with a clear message indicating that he just bought these Sandwiches, and that they'll be on their way around lunch time.

**Comment by toonborgers** [comment]
Fixed in pull request #24
