### ISSUE TITLE
Opening Hours

### ISSUE THREAD

**Issue by Sch3lp** [Sch3lp/FiAngulartje#6]
A reusable component/directive to show the opening hours.

Use microdata attributes so google can parse it in their results:
`<li><data itemprop="openingHours" datedata="Mo 09:00-17:30"><span class="day">Monday:</span> <span class="hours">09:00-17:30</span></data></li>`

Get openinghours from a Resource `/v1/openinghours` that returns JSON:
```json
[
{
    "day":"1",
    "hours":[{"from":"09:00","until":"12:00"},{"from":"12:30","until":"17:00"}]
},
{
    "day":"2",
    "hours":[{"from":"09:30","until":"12:30"}]
}
]
```
1 = monday. Because we're living in fucking Europe.

**Comment by toonborgers** [comment]
[Here](https://developers.google.com/webmasters/business-location-pages/schema.org-examples) is a link with some more information and [here](http://schema.org/FoodEstablishment) is the full schema for food places.

**Comment by toonborgers** [comment]
Fixed with [this](https://github.com/Sch3lp/FiAngulartje/pull/18) pull request
